[package]
name = "echor"
version = "0.1.0"
edition = "2021"
authors = [ "William Noble" ]

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3.0.3"