[package]
name = "catr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_cmd = "2.0.0"
predicates = "2.0.0"

[dependencies]
clap = "2.33"
rand = "0.8.5"